[tool.poetry]
name = "fastapi-study"
version = "0.1.0"
description = ""
authors = [
    "codepanda <codepanda@qq.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pytest = "^8.3.4"
httpx = "^0.28.1"
pytest-asyncio = "^0.25.2"
anyio = "^4.8.0"
asgi-lifespan = "^2.1.0"

[tool.poetry.dependencies.fastapi]
extras = [
    "all",
]
version = "^0.115.6"

[tool.poetry.dependencies.aerich]
extras = [
    "toml",
]
version = "^0.8.1"

[tool.poetry.dependencies.uvicorn]
extras = [
    "standard",
]
version = "^0.34.0"

[tool.poetry.dependencies.tortoise-orm]
extras = [
    "aiosqlite",
]
version = "^0.23.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-asyncio = "^0.25.2"
anyio = "^4.8.0"
httpx = "^0.28.1"
black = "^24.10.0"
isort = "^5.13.2"
mypy = "^1.14.1"
flake8 = "^7.1.1"
pytest-cov = "^6.0.0"
pytest-xdist = "^3.6.1"

[tool.aerich]
tortoise_orm = "app.config.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"

[pytest]
asyncio_mode = "auto"
asyncio_backend = "anyio"
asyncio_default_fixture_loop_scope = "function"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"