[tool.aerich]
tortoise_orm = "app.config.TORTOISE_TEST_ORM"
location = "./migrations"
src_folder = "./."

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[pytest]
asyncio_mode = "auto"
asyncio_backend = "anyio"
asyncio_default_fixture_loop_scope = "function"
